//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoice.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long ID { get; set; }
        public long CompanyId { get; set; }
        public int FormId { get; set; }
        public string Series { get; set; }
        public int No { get; set; }
        public string SecureCode { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public int PaymentTypeID { get; set; }
        public string Note { get; set; }
        public long ProductID { get; set; }
        public decimal Tax { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int UnitID { get; set; }
        public int Quantity { get; set; }
        public decimal VAT { get; set; }
        public Nullable<decimal> VATCost { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalServiceCost { get; set; }
        public Nullable<decimal> TotalPaymentCost { get; set; }
        public string InWord { get; set; }
        public Nullable<long> TypeID { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Form Form { get; set; }
        public virtual InvoiceType InvoiceType { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Product Product { get; set; }
    }
}
