//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoice.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string Priod { get; set; }
        public Nullable<int> Year { get; set; }
        public string Pattern { get; set; }
        public string Serial { get; set; }
        public Nullable<int> SumNoInventoryNo { get; set; }
        public Nullable<int> StartNoInventroryNo { get; set; }
        public Nullable<int> ToInventroryNo { get; set; }
        public Nullable<int> FromBuyNo { get; set; }
        public Nullable<int> ToBuyNo { get; set; }
        public Nullable<int> TotalInvoiceIssued { get; set; }
        public Nullable<int> FromInvoiceIssuedNo { get; set; }
        public Nullable<int> ToInvoiceIssuedNo { get; set; }
        public Nullable<int> TotalUsed { get; set; }
        public Nullable<int> TotalDelete { get; set; }
        public string NoDelete { get; set; }
        public Nullable<int> SumLost { get; set; }
        public string NoLost { get; set; }
        public Nullable<int> SumCancel { get; set; }
        public string NoCancel { get; set; }
        public Nullable<int> TotalEndingStock { get; set; }
        public Nullable<int> FromEndingStockNo { get; set; }
        public Nullable<int> ToEndingStockNo { get; set; }
    }
}
