//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoice.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenCreateDate { get; set; }
        public string PasswordToken { get; set; }
        public Nullable<System.DateTime> PasswordTokenCreateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
